// lang-es.ts

export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {

    'Back': 'Retour',
    'Dashboard': 'Tableau de Bord',
    'My Planning': 'Mon Planning',
    'My profile': 'Mon profil',
    'My company': 'Mon Entreprise',
    'Logout': 'Déconnexion',
    'Items per page': 'Eléments par page',
    'Accountancy': 'Comptabilité',
    'Payments': 'Encaissements',
    'Payment': 'Encaissement',
    'Expenses': 'Dépenses',
    'Expense': 'Dépense',
    'Reporting': 'Statistiques',
    'Settings': 'Paramètres',
  

    'Add a product': 'Ajouter un produit',
    'Create a new': 'Créer un nouveau',
    'product': 'produit',
    'Products': 'Produits',
    'Create an new product': 'Créer un nouveau produit',
    'List': 'Liste',
    'Name': 'Nom',
    'Price without taxes': 'Prix HT',
    'Product Name': 'Nom du Produit',
    'companie': 'Entreprise', 
    'Height': 'Hauteur',
    'Width': 'Largeur',
    'Depth': 'Profondeur',
    'CostPrice': 'Coût',
    'Selling Price': 'Prix de vente',
    'Save': 'Sauvegarder',
    'Delete': 'Supprimer',

    'Users': 'Contacts',
    'User': 'Contact',
    'Team': 'Équipe',
    'External Contact': 'Contact Externe',
    'Create a new team member': 'Créer un nouveau membre interne',
    'Create a new external member': 'Créer un nouveau contact externe',
    'Firstname': 'Prénom',
    'Lastname': 'Nom',
    'Type User': 'Fonction',
    'Phone Number': 'Téléphone',
    'Address': 'Adresse',
    'additional address': 'Complément Adresse',
    'city': 'Ville',
    'City': 'Ville',
    'state': 'Pays',
    'State': 'Etat',
    'zip': 'Code Postal',
    'Zip': 'Code Postal',
    'Country': 'Pays',
    'Acces Code': 'Code Entrée',
    'Done': 'Enregistrer',
    'accessCode': 'Code Immeuble',
    'Acces type': 'Type d´accès',
    'floor': 'Etage',
    'Floor': 'Etage',
    'Number': 'N°',
    'Other': 'Autre',
    'Identity': 'Détails',
    'Details': 'Coordonnées',
    'Calendar Color': 'Couleur du calendrier',
    'Surface': 'Surface',
    'Phone': 'Téléphone',
    'Add Picture': 'Ajouter image',
  

    'Quotes': 'Devis',
    'quote': 'devis',
    'Create a new quote': 'Créer un nouveau Devis',
    'Assigned to me': 'Assigné à Moi',
    'Owner': 'Propriétaire',
    'Download PDF': 'Télécharger PDF',
    'Customer': 'Client',
    'Customers': 'Clients',
    'Supplier': 'Fournisseur',
    'Suppliers': 'Fournisseurs',
    'Estimate Number': 'Numéro du devis',
    'Issue Date': 'Date',
    'Expiry Date': 'Date de Validité',
    'Currency': 'Devise',
    'Estimate Template': 'Modèle de Devis',
    'Amounts are': 'Les montants sont',
    'Discount': 'Remise',
    'Subject': 'Sujet',
    'Add Row': 'Ajouter Ligne',
    'Item': 'Objet',
    'Quantity': 'Quantité',
    'nameTemplate': 'Nom du modèle',
    'templateQuote': 'Recherche',
    'Save TemplateQuote': 'Sauvegarder le Modèle',
    'Add new one': 'Ajouter',
    'Create a new Paiement': 'Nouveau Paiement',
    'Please Select': 'Mode de Paiement',
    'Amount': 'Montant',

    'Today': 'Aujourd´hui',


    'project': 'Projet',
    'Projects': 'Projets',
    'Ref': 'Nom',


    'task': 'tâche',
    'Tasks': 'Tâches',
    'Add a project': 'Ajouter un projet',


    'Pending Approval': 'Attente de signature',
    'right': 'droit',
    'Rights': 'Droits',
  
    'Search': 'Recherche',

};
